spring.application.name=devops

#Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/devops_db
spring.datasource.username=postgres
spring.datasource.password=123456

#Atualização automatica do esquema do banco de dados
spring.jpa.hibernate.ddl-auto=update

#Mostrar as consultas SQL no console
spring.jpa.show-sql=true

#Não mostrar as formatações SQL
spring.jpa.properties.hibernate.format_sql=false

#Configurações da porta do servidor
server.port=8080
#Configurações de Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adryan.thiago1509@gmail.com
spring.mail.password=roqg idwc icpf ikrc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
